### ISSUE TITLE
CentricityNow Error when Registrying

### ISSUE THREAD

**Issue by bowcraft** [virencehealth/apiserver.virencehealth.com#65]
When trying to setup CentricityNow to use our FHIR API, we get an error in the \jboss\standalone\log\CentricityFHIR.log
 The first few lines of the error are
Java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
                at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450) ~[ojdbc6.jar:11.2.0.3.0]
                at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399) ~[ojdbc6.jar:11.2.0.3.0]
I can send more logs if needed.
Thanks

**Comment by bowcraft** [comment]
The version we are running is 9.12.3_9 (3440) / DB 9.12.3_9/SP 3
I spoke with Kadar and he told me that it does not work in 9.12.3, has to be V.19 for this to work.
